version: '3'

volumes:
  static:
  media:

services:

  backend:
    build: ./currency_converter/
    env_file: .env
    volumes:
      - static:/var/html/static
      - media:/var/html/media

  gateway:
    container_name: currency_converter_gateway
    build: ./nginx/
    volumes:
      - static:/var/html/static
      - media:/var/html/media
    ports:
      - 8000:80
    depends_on:
      - backend
