# Generated by Django 4.2.9 on 2024-01-19 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Английское название')),
                ('name_ru', models.CharField(max_length=50, verbose_name='Русское название')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='ISO код')),
                ('url_image', models.URLField()),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'db_table': 'currency',
            },
        ),
        migrations.CreateModel(
            name='EchangeRateToUsd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(verbose_name='Он же PRICE')),
                ('flowrate24', models.FloatField(verbose_name='Он же CHANGE24HOUR')),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.currency')),
            ],
        ),
    ]
