# Generated by Django 4.2.9 on 2024-06-27 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Английское название')),
                ('name_ru', models.CharField(max_length=50, verbose_name='Русское название')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='ISO код')),
                ('type', models.CharField(blank=True, choices=[('Fiat', 'fiat'), ('Crypto', 'crypto')], max_length=50)),
                ('url_image', models.URLField(blank=True, null=True, verbose_name='Ссылка на изображение')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'db_table': 'currency',
            },
        ),
        migrations.CreateModel(
            name='CurrencyEchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(null=True, verbose_name='Он же PRICE')),
                ('flowrate24', models.FloatField(null=True, verbose_name='Он же CHANGE24HOUR')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echangerate', to='currency.currency')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы валют',
                'get_latest_by': 'last_update',
            },
        ),
    ]
