# Generated by Django 4.2.9 on 2024-07-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_currency_image_currency_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(blank=True, max_length=3, unique=True, verbose_name='ISO код'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Английское название'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name_ru',
            field=models.CharField(blank=True, max_length=50, verbose_name='Русское название'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='sign',
            field=models.CharField(blank=True, default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currency',
            name='url_image',
            field=models.URLField(blank=True, default=123, verbose_name='Ссылка на изображение'),
            preserve_default=False,
        ),
    ]
