# Generated by Django 4.2.9 on 2024-04-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_echangeratetousd_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='type',
            field=models.CharField(choices=[('FIAT', 'fiat'), ('CRYPTO', 'crypto')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
