# Generated by Django 4.2.9 on 2024-05-07 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_currency_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyEchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(null=True, verbose_name='Он же PRICE')),
                ('flowrate24', models.FloatField(null=True, verbose_name='Он же CHANGE24HOUR')),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы валют',
                'get_latest_by': 'last_update',
            },
        ),
        migrations.AlterField(
            model_name='currency',
            name='type',
            field=models.CharField(choices=[('Fiat', 'fiat'), ('Crypto', 'crypto')], max_length=50),
        ),
        migrations.AlterField(
            model_name='currency',
            name='url_image',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на изображение'),
        ),
        migrations.DeleteModel(
            name='EchangeRateToUsd',
        ),
        migrations.AddField(
            model_name='currencyechangerate',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echangerate', to='currency.currency'),
        ),
    ]
