# Generated by Django 4.2.9 on 2024-07-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_alter_currency_code_alter_currency_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='sign',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
